### ISSUE TITLE
This lab will fail for text strings under 10 characters or duplicate tips

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-students/ruby-posting-requests-v-000#781]
"meta": {
        "code": 400,
        "errorType": "param_error",
        "errorDetail": "Text must be at least 10 characters and less than 200.",
        "requestId": "5c74f290351e3d13ab770c2a"
    }

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
